# Generated by Django 4.1.13 on 2024-04-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_projet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numMattr', models.CharField(max_length=40, unique=True)),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('mobile_number', models.CharField(blank=True, max_length=10)),
                ('location', models.TextField(max_length=255)),
                ('dateBirth', models.DateField(verbose_name='%m/%d/%Y')),
            ],
        ),
    ]
