# Generated by Django 4.1.13 on 2024-04-25 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_students'),
    ]

    operations = [ 
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('etudiants', models.ManyToManyField(to='main_app.students')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.projet')),
            ],
        ),
    ]
