# Generated by Django 3.1.1 on 2024-04-29 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_projet_description_alter_students_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='niveau',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.course'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='students',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
