# Generated by Django 3.1.1 on 2024-04-29 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20240429_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrerequisGroupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=40)),
                ('status', models.BooleanField(default=False)),
                ('delais', models.IntegerField()),
                ('niveau', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.course')),
            ],
        ),
    ]
