# Generated by Django 5.0 on 2024-05-05 04:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_projet_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prerequisgroupe',
            name='delais',
        ),
        migrations.AddField(
            model_name='prerequisgroupe',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prerequisgroupe',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
