# Generated by Django 5.0 on 2024-05-05 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_prerequisgroupe_delais_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequisgroupe',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
