# Generated by Django 5.0 on 2024-05-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_prerequisgroupe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='etudiants',
            field=models.ManyToManyField(related_name='groupes', to='main_app.students'),
        ),
    ]
