# Generated by Django 5.0 on 2024-05-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_groupe_niveau_groupe_prerequisgroupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
