# Generated by Django 5.0 on 2024-05-10 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_groupe_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupe',
            name='etudiants',
        ),
    ]
