# Generated by Django 5.0 on 2024-05-10 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_groupeetudiant_groupe_etudiants'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupeetudiant',
            name='prerequisGroupe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.prerequisgroupe'),
        ),
    ]
